### ISSUE TITLE
[FEAT] Criação da classe PerfilService para fazer a validação das chamadas ao banco

### ISSUE THREAD

**Issue by NathanJFA** [universi-me/universi-api#163]
# -- Feature --

## Descrição

Criação de uma classe service para realizar a validação ded todas as chamadas ao banco, 
## Motivação

Essa feature serve para criar uma maior segurança e estabilizade ao sistema, prevenindo que valores inválidos sejam chamados lançados na base de dados.

**Comment by JHDsBR** [comment]
Eu acabei criando por necessidade, mas só implementei 1 método, então é isso, é só ir lá e implementar o restante.

**Comment by NathanJFA** [comment]
Tranquilo
