### ISSUE TITLE
[FEAT] Criação da classe CompetenciaException

### ISSUE THREAD

**Issue by NathanJFA** [universi-me/universi-api#166]
# -- Feature --

## Descrição

Criação de uma classe de exceção chamada CompetenciaException, que será utilizada na CompetenciaService.
## Motivação

É um recurso afim de organizar melhor o tratamento de exceções.

**Comment by JHDsBR** [comment]
Eu não tinha visto essa issue, ai acabei criando outra com o mesmo propósito e já completei
