### ISSUE TITLE
[FEAT] Criação da classe UsuarioService

### ISSUE THREAD

**Issue by FranciscoVieiraN** [universi-me/universi-api#168]
# -- Feature --

## Descrição
Criação da classe Service para a entidade Ususario

## Motivação
Para facilitar a manipulação do usuário.

**Comment by julio-ufpb** [comment]
ja temos o service do usuario, classe SecurityUserDetailsService, podemos alterar essa issue para change e renomear SecurityUserDetailsService para UsuarioService ou fechar a issue
