### ISSUE TITLE
[BUG] Atualizar o Perfil do usuário apaga a foto cadastrada

### ISSUE THREAD

**Issue by adriannfernandes** [universi-me/universi-api#224]
# -- Bug Report 🐛 --

## Comportamento esperado

Ao atualizar os dados no perfil é esperado que a foto que foi escolhida continue.
## Comportamento atual

Ao atualizar qualquer dado no perfil a foto desaperece.
## Passos para reproduzir
1º Adicione uma foto de perfil.
2º Vá na opção "Meu Perfil"
3º Procure a opção "Editar Perfil"
4º Atualize qualquer dado no perfil (nome, bio, sexo)

1.
2.
3.
4.

**Comment by julio-ufpb** [comment]
no pull verificar permissão ao editar perfil (#221), nesse commit tbm foi adicionado a verificação de nulo em todos os parametros, o que coincidiu tbm com a correção desse bug.
