### ISSUE TITLE
[CHANGE] Retornar apenas usuarios que tenham competências cadastradas

### ISSUE THREAD

**Issue by NathanJFA** [universi-me/universi-api#255]
# -- Mudanças--

## Descrição

Ao consultar usuário na tela de recomendações, apenas retornar usuários que possuem competências cadastradas
## Motivação

Para não ocasionar em bug, onde o usuário consegue escrever a mensagem mas não consegue escolher a competência.

**Comment by julio-ufpb** [comment]
Agora a competência é pre cadastrada, assim podemos fechar a issue.
