### ISSUE TITLE
[FEATURE]: Adicionar dependência do flyway ao projeto

### ISSUE THREAD

**Issue by Alvaro-Antonio** [universi-me/universi-api#371]
# -- Feature --

## Descrição
Adicionar dependência flyway para versionamento e gerenciamento de banco de dados

## Motivação
Facilitar migração de dados e atualizações

**Comment by clebsonf** [comment]
Ao adicionar o flyway, adicionar uma migration com o user admin
https://github.com/universi-me/universi-api/blob/development/src/main/java/me/universi/Sys.java#L55-L70
