### ISSUE TITLE
[FEAT] Adicionar gestão de Competências

### ISSUE THREAD

**Issue by adriannfernandes** [universi-me/universi-api#43]
# -- Feature --

## Descrição

Adicionar no perfil do usuário todas as suas competências e possibilitar a criação de novas competências

**Comment by mikaoliveira** [comment]
Essa issue foi criada para implementar os metodos listar e criar competencia? 
se foi pra isso, a gente ja fez, pode excluir.

**Comment by adriannfernandes** [comment]
Essa issue é para implementar essas funcionalidades no Perfil.
