### ISSUE TITLE
[FEAT] Profile image endpoint

### ISSUE THREAD

**Issue by NiiMiyo** [universi-me/universi-api#476]
# -- Feature --

## Descrição

Add a fixed endpoint, for example `/api/profile/image/<username>` that returns user profile image.
- Profile Image: `/api/profile/image/<username>`
- Group Image: `/api/group/image/<username>`
- Group Banner: `/api/group/banner/<username>`

## Motivação

Simplify front-end logic by having a fixed endpoint instead of trying to guess the image URL right.

**Comment by julio-ufpb** [comment]
esses endpoints da imagem seria um 302 redirect para a url da imagem? , _/api/profile/image/nome_usuario_ , _/api/group/image/user_do_grupo_
