### ISSUE TITLE
[BUG] Cadastro Usuário: Ao se cadastrar, o sistema deve abrir a página de configuração do perfil, para que o usuário possa editar sua foto.

### ISSUE THREAD

**Issue by rodrigor** [universi-me/universi-api#725]
![Image](https://github.com/universi-me/universi-front/assets/288272/28e4fab7-7049-4ad4-8f28-4b292fc44d27)

**Comment by NiiMiyo** [comment]
Adicionar verificação de imagem em https://github.com/universi-me/universi-api/blob/087707394ddbff9c7fbf598b80827df1491dbb9a/src/main/java/me/universi/user/services/UserService.java#L418-L427
